# -*- coding: utf-8 -*-
"""Health care Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ma7nBYgPMcZD8rkngqR1JcE9GGIqO40V

**INSTALL FAKER**
"""

pip install faker

from faker import Faker

fake = Faker()

"""**DATA SET**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = []

for i in range(10000):
    data.append({
        "Patient_ID": i+1,
        "Age": np.random.randint(20, 81),
        "Gender": np.random.choice(["Male", "Female"]),
        "Blood_Pressure": np.random.randint(80, 181),
        "Sugar_Level": np.random.randint(70, 201),
        "Cholesterol": np.random.randint(150, 301),
        "Heart_Rate": np.random.randint(60, 121)
    })

df = pd.DataFrame(data)
df.head()

df.info()
df.isnull().sum()
df.describe()

def risk(row):
    if row["Blood_Pressure"] > 140 or row["Sugar_Level"] > 180 or row["Cholesterol"] > 240:
        return "High"
    elif row["Blood_Pressure"] > 120 or row["Sugar_Level"] > 140:
        return "Medium"
    else:
        return "Low"

df["Risk"] = df.apply(risk, axis=1)

high_risk = df[df["Risk"] == "High"]
high_risk.head()

df["Age_Group"] = pd.cut(df["Age"],
                        bins=[20,30,40,50,60,70,80],
                        labels=["20-30","30-40","40-50","50-60","60-70","70-80"])

df.groupby("Age_Group")["Blood_Pressure"].mean()

df.groupby("Gender").mean(numeric_only=True)

df["Risk"].value_counts()

"""**BAR CHART**"""

df["Risk"].value_counts().plot(kind="bar")
plt.title("Risk Distribution")
plt.xlabel("Risk")
plt.ylabel("Count")
plt.show()

"""**PIE CHART**"""

df["Gender"].value_counts().plot(kind="pie", autopct='%1.1f%%')
plt.title("Gender Distribution")
plt.ylabel("")
plt.show()

"""**HISTOGRAM**"""

plt.hist(df["Age"], bins=20)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

"""**SCATTER PLOT**"""

plt.scatter(df["Age"], df["Blood_Pressure"], alpha=0.1)
plt.title("BP vs Age")
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.show()

"""**BOX PLOT**"""

plt.boxplot(df["Cholesterol"])
plt.title("Cholesterol Boxplot")
plt.show()

"""**HEATMAP**"""

corr = df.corr(numeric_only=True)

plt.imshow(corr)
plt.colorbar()

plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)

plt.title("Correlation Heatmap")
plt.show()